### ISSUE TITLE
Error building base layers

### ISSUE THREAD

**Issue by budhrg** [ooyala/atlantis-aquarium#24]
I am getting following error while building base layers:
```
vagrant@atlantis-aquarium-vm:~$ atlantis-aquarium build-layers --base
{"build"=>false, "<component>"=>[], "--compile"=>0, "--no-cache"=>false, "--image"=>0, "--instance"=>"all", "--help"=>false, "-c"=>false, "start"=>false, "restart"=>false, "stop"=>false, "ssh"=>false, "command"=>0, "atlantis"=>false, "<arguments>"=>[], "provision"=>false, "register-components"=>false, "base-cluster"=>false, "build-layers"=>true, "--base"=>true, "--builder"=>false, "zookeeper"=>false}
cd ./data/builder; ssh `cat ip` "sed 's;^chroot /tmp/base /bin/bash -c \"su - -c /sbin/provision\"$;chroot /tmp/base /bin/bash -c \"su - -c http_proxy=http://172.17.42.1:3128\\\\ /sbin/provision\";' /opt/atlantis/builder/bin/atlantis-mkbase -i"
sed 's;^exec > /sbin/provision_type.log 2>&1$;&\nexport http_proxy=http://172.17.42.1:3128;;s;https://go.googlecode.com/files/go;http://go.googlecode.com/files/go;' \$d/sbin/provision_type -i
cd ./data/builder; ssh `cat ip` "for d in /opt/atlantis/builder/layers/builder/*; do sed 's;^exec > /sbin/provision_type.log 2>&1$;&\nexport http_proxy=http://172.17.42.1:3128;;s;https://go.googlecode.com/files/go;http://go.googlecode.com/files/go;' \$d/sbin/provision_type -i; done"
cd ./data/builder; ssh `cat ip` "REGISTRY=registry.aquarium /opt/atlantis/builder/bin/atlantis-mkbase -f images/tiny.tgz"
stdin: is not a tty
+ exec
64ef5a51595c8fe6698928bf755587bf18f5063b866f279b86f3af6810b7edfa
time="2015-09-16T08:18:37Z" level="fatal" msg="Error: v1 ping attempt failed with error: Get http://registry.aquarium/v1/_ping: dial tcp: i/o timeout"
```

I am using `ghao/atlantis-aquarium` box.

I am still getting error when setting my registry ip `172.17.0.3` to `registry.aquarium` in `/etc/hosts` file.
Any prerequisite to set it up?
Am I missing something here?

**Comment by ghao-ooyala** [comment]
I was able to run the command.

{"build"=>false, "<component>"=>[], "--compile"=>0, "--no-cache"=>false, "--image"=>0, "--instance"=>"all", "--help"=>false, "-c"=>false, "start"=>false, "restart"=>false, "stop"=>false, "ssh"=>false, "command"=>0, "atlantis"=>false, "<arguments>"=>[], "provision"=>false, "register-components"=>false, "base-cluster"=>false, "build-layers"=>true, "--base"=>true, "--builder"=>false, "zookeeper"=>false}
Restarting in VM...
{"build"=>false, "<component>"=>[], "--compile"=>0, "--no-cache"=>false, "--image"=>0, "--instance"=>"all", "--help"=>false, "-c"=>false, "start"=>false, "restart"=>false, "stop"=>false, "ssh"=>false, "command"=>0, "atlantis"=>false, "<arguments>"=>[], "provision"=>false, "register-components"=>false, "base-cluster"=>false, "build-layers"=>true, "--base"=>true, "--builder"=>false, "zookeeper"=>false}
cd ./data/builder; ssh `cat ip` "sed 's;^chroot /tmp/base /bin/bash -c \"su - -c /sbin/provision\"$;chroot /tmp/base /bin/bash -c \"su - -c http_proxy=http://172.17.42.1:3128\\\\ /sbin/provision\";' /opt/atlantis/builder/bin/atlantis-mkbase -i"
sed 's;^exec > /sbin/provision_type.log 2>&1$;&\nexport http_proxy=http://172.17.42.1:3128;;s;https://go.googlecode.com/files/go;http://go.googlecode.com/files/go;' \$d/sbin/provision_type -i
cd ./data/builder; ssh `cat ip` "for d in /opt/atlantis/builder/layers/builder/*; do sed 's;^exec > /sbin/provision_type.log 2>&1$;&\nexport http_proxy=http://172.17.42.1:3128;;s;https://go.googlecode.com/files/go;http://go.googlecode.com/files/go;' \$d/sbin/provision_type -i; done"
cd ./data/builder; ssh `cat ip` "REGISTRY=registry.aquarium /opt/atlantis/builder/bin/atlantis-mkbase -f images/tiny.tgz"
stdin: is not a tty
+ exec
788a18c1331dee5935b69e92531b07cc7df4a933959ab1cc075c108c7edf7747
The push refers to a repository [registry.aquarium/base/precise64-0.1.0] (len: 1)
Sending image list
Pushing repository registry.aquarium/base/precise64-0.1.0 (1 tags)
788a18c1331d: Pushing
788a18c1331d: Buffering to disk
788a18c1331d: Image successfully pushed
Pushing tag for rev [788a18c1331d] on {http://registry.aquarium/v1/repositories/base/precise64-0.1.0/tags/latest}
Connection to 127.0.0.1 closed.

Adding registry.aquarium to /etc/hosts does not work. dnsmasq running in VM is used to resolve registry.aquarium into ip; make sure the dnsmasq is running and this file contain the right setting:

vagrant@atlantis-aquarium-vm:/etc/aquarium$ cat /etc/aquarium/hosts-aquarium 
172.17.0.2 zookeeper.aquarium
172.17.0.3 registry.aquarium
172.17.0.4 builder.aquarium

If dns lookup is working, you should be able to do this from within builder container

root@550c99b6148b:~# curl registry.aquarium:80
go-docker-registry server

**Comment by budhrg** [comment]
@ghao-ooyala . Configured `dnsmasq`. Building layers working properly now
