### ISSUE TITLE
Proposal : Commit Id or tag based pinning of component repo

### ISSUE THREAD

**Issue by budhrg** [ooyala/atlantis-aquarium#26]
Hi,

Since [this code snippet](https://github.com/ooyala/atlantis-aquarium/blob/master/bin/gather-files#L27) is pointing to `stabilize` branch which should be updated to `master` branch.

However, master branch may not always be stable so I would to propose for two ideas:
- **Tag**: In this case, we need to tag every repo with working commit it.
- **Commit Id**: In this case, we will update [`repos-config.yml`](https://github.com/ooyala/atlantis-aquarium/blob/master/repos-config.yml) file to include working commit id or master if not mentioned and then update [this code snippet](https://github.com/ooyala/atlantis-aquarium/blob/master/bin/gather-files#L27) as per required changes.

What do you think about it?
Any other suggestion?

**Reason for this proposal**:
I have encountered issues while building base layer(`some checksum error`). 
I have recorded my last successful build with aquarium as:
```
# Atlantis Aquarium:
Branch  - master
Commit  - 4ec15c80c3475cd8dcc1641c098af62536f0113b
Message - Building builder to use toml based configuration for daemon

# Atlantis Builder:
Branch  - toml_based_builder
Commit  - 2beef254dd1532e0b98cf79a4a3c115b154d5bdf
Message - Added github.com/jigish/go-flags submodule

# Atlantis Manager:
Branch  - local
Commit  - 7b6bcf80775f2b3135168e1ddb5f1c7f5e573fa3
Message - Added reinstall local manager script

# Atlantis Router:
Branch  - master
Commit  - 748f115411931002fb701e3932d152d1c44d9ead
Message - Merge pull request #20 from budhrg/master

# Atlantis Supervisor:
Branch  - master
Commit  - 0f1b6560a00ec06627527b126f1858589159d25b
Message - Merge remote-tracking branch 'ooyala/master'

# Go docker Registry:
Branch  - master
Commit  - 72764a5b76dcb2f4b912690112dc79affbf0ed4a
Message - Renamed atlantis-registry to go-docker-registry
```

**Comment by edanaher** [comment]
We should switch it to master.

Master should always be stable.  If it isn't, then it fixing it is one of the top priorities.  Since aquarium is used for development, it's a good way to find out that things are broken.

**Comment by ghao-ooyala** [comment]
I need to clean up this line, with a few other things.

**Comment by budhrg** [comment]
Ok @edanaher and @ghao-ooyala .
